### ISSUE TITLE
VERSION

### ISSUE THREAD

**Issue by pbelmann** [CAMI-challenge/AMBER#13]
AMBER should be versioned following the semantic versioning conventions: http://semver.org/
We should create a setup.cfg which states the current release/version.
This information could also be parsed by various scripts and included in a pdf/html/png, ... . The result of AMBER should always state by which release it was produced. 
The config is also necessary for issue #5 .

**Comment by fernandomeyer** [comment]
Version is stated in version.py and used throughout.
