### ISSUE TITLE
Create GitHub Page

### ISSUE THREAD

**Issue by pbelmann** [CAMI-challenge/AMBER#14]
It would be nice to have Github Page https://pages.github.com/ that just shows the current html that AMBER can produce. This would be just another branch with in this repo.

**Comment by pbelmann** [comment]
Page is now available at https://cami-challenge.github.io/AMBER/

**Comment by alicemchardy** [comment]
nice!

The names of the programs in the first produced overview table could be made a bit smaller.



best, Alice

Prof. Alice C. McHardy
Computational Biology of Infection Research
Helmholtz Centre for Infection Research
________________________________

**Comment by pbelmann** [comment]
Ok. I will update the size in my next PR.
