### ISSUE TITLE
Output metrics bp vs seq.

### ISSUE THREAD

**Issue by ohickl** [CAMI-challenge/AMBER#38]
Hi,
could you clarify the difference between the AMBER 2.x seq and bp based metrics? As you explained in #36, Average purity (bp) stems from equation 6 in the original paper. This would then be `Average purity (bp)` of `Quality of bins: all bins have the same weight` in the `index.html` output? Does the seq based metric then mean, the value is based on the number of contigs from the most abundant gold standard genome in each bin? Does that value deviate from the bp metric, because of different contig lenghts and thus a large contig of the "correct" genome will not increase e.g. the seq purity value but the bp one? If so why would we care about that? Wouldn't the bp based measure always be more informative in showing how close bins are to the gold standard?

Best 
Oskar

**Comment by fernandomeyer** [comment]
Hello, in the metrics per sequence (seq), true positives, false positives, and false negatives are measured in number of contigs. However, to determine the most abundant genome in a bin, the number of base pairs is used, i.e. it is used in both the bp and seq metrics. In the bp metrics, longer contigs have higher weight, whereas in the seq metrics, all contigs contribute the same. I have added an example page with updated tooltips explaining the metrics: https://cami-challenge.github.io/AMBER/cami_ii_mouse_gut/
I hope this helps.

**Comment by ohickl** [comment]
It does, thanks for the clarification!
