### ISSUE TITLE
amber only considers bins with completeness > 0 ?

### ISSUE THREAD

**Issue by dpellow** [CAMI-challenge/AMBER#43]
Hi,
I have a sample that I want to bin only a fraction of - for example I have 10 bins in the gold standard and the sample has a bunch of  other sequences that I don't want to put into bins. A binning tool creates 20 bins, of which 15 match to 5 gold standard bins. IE there are 5 bins created by the binner which don't match to any gold standard bin. Is there any way for amber to handle a situation like this?

(I can send you more details and example data by email if you wish - mine is dpellow <at> post.tau.ac.il)

**Comment by fernandomeyer** [comment]
Completeness is a measure of how much of the genomes  in the gold standard have been recovered by a genome binner, i.e. how much of their sequences have been binned together. Sequences that are eventually in predicted bins but not in the gold standard are not representing any genome recovery and cannot even be assessed if they belong together in the same bin, therefore AMBER ignores such sequences. Entire bins can be ignored if no sequence is in the gold standard.
The completeness of a genome can be zero, for instance, if a genome binner does not bin any of its sequences.
