### ISSUE TITLE
Issue when running add_length_column.py

### ISSUE THREAD

**Issue by polinanvkv** [CAMI-challenge/AMBER#44]
I am trying to call the help for the script with `python3 add_length_column.py -h`. And I am getting the following output: 
```
Traceback (most recent call last):
  File "/home/users/pnovikova/binning-refinement/scripts/add_length_column.py", line 26, in <module>
    import argparse_parents
ModuleNotFoundError: No module named 'argparse_parents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/pnovikova/binning-refinement/scripts/add_length_column.py", line 30, in <module>
    import argparse_parents
ModuleNotFoundError: No module named 'argparse_parents'
```
The `argparse` module is installed. And as far as I see from google, there's no such module as `argparse_parents`. What am I doing wrong? 

Thanks!

**Comment by fernandomeyer** [comment]
The `add_length_column.py` tool belongs to the AMBER package, and so does argparse_parents. According to the traceback, you copied it to another directory which is not related to AMBER.

**Comment by polinanvkv** [comment]
indeed, it is the case. thanks, resolved!
