### ISSUE TITLE
a data-related problem

### ISSUE THREAD

**Issue by Huangpq2019** [CAMI-challenge/AMBER#45]
Dear,
In the article "Tutorial: assessing metagenomics software with the CAMI benchmarking toolkit",  the CAMI II mouse gut dataset used is the short reads of 64 samples? If so, where can I download this dataset? I only found pacbio scaffolds related data in https://openstack.cebitec.uni-bielefeld.de:8080/swift/v1/CAMISIM_MOUSEGUT, but no short reads.

Looking forward to your reply, thanks!

**Comment by fernandomeyer** [comment]
Yes, the CAMI II mouse gut short-read data were used and made available. To get the full list of files, use the command:

`java -jar camiClient.jar -l https://openstack.cebitec.uni-bielefeld.de:8080/swift/v1/CAMISIM_MOUSEGUT`

The short reads are in the following files:
```
19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_0/reads/anonymous_reads.fq.gz
19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_1/reads/anonymous_reads.fq.gz
...
19122017_mousegut_scaffolds/2017.12.29_11.37.26_sample_63/reads/anonymous_reads.fq.gz
```
The gold standard cross-sample assembly is in: `19122017_mousegut_scaffolds/anonymous_gsa_pooled.fasta.gz`

The dataset is also available at https://doi.org/10.4126/FRL01-006421672 (though _Publisso's_ download link appears to be temporarily broken).
