### ISSUE TITLE
Other problem.

### ISSUE THREAD

**Issue by zhang570221322** [CAMI-challenge/AMBER#46]
Hi,  Great Jobs. I'm involved in it. But why can't I access this site: https://data.cami-challenge.org.  The log shows that it seems http://data.cami-challenge.org closed the connection.
It's very confusing that I can enter this website: https://microbiome-cosi.org/cami/.

**Comment by fernandomeyer** [comment]
Thanks for the message. I was told that one of the servers is being upgraded and should be back online soon, hopefully today or tomorrow.

**Comment by zhang570221322** [comment]
Thanks. I get.
