### ISSUE TITLE
Updates for AMBER requirements

### ISSUE THREAD

**Issue by yazhinia** [CAMI-challenge/AMBER#52]
Dear developer,
           I found while setting up AMBER in the system via pip that some more packages with specific versions should be installed. 
1) scipy=1.8.0 (to be compatible with NumPy 1.18.3)
2) jinja2=2.10.1
3) MarkupSafe=2.0.1
4) Flask=1.0.3

It would be useful if it is included in the prerequisite file for future users.

Thank you.

Best,
Yazhini

**Comment by fernandomeyer** [comment]
AMBER v2.0.4 has been released with updated requirements.
