### ISSUE TITLE
mixed dtype for BINID can cause bins with same IDs to be split into separate bins

### ISSUE THREAD

**Issue by mattheatley** [CAMI-challenge/AMBER#54]
if BINID is a mixture of strings/ints I've noticed that individual int values can be imported as both strings and ints essentially splitting a single bin into two. 

I believe it's an issue with how pandas imports the dataframes and may only happen with large files. the issue appears to be resolved by using either int or string values for BINID

**Comment by fernandomeyer** [comment]
Thanks for reporting this. One can try setting `df['BINID'] = df['BINID'].astype(pd.StringDtype())` in function [load_binnings](https://github.com/CAMI-challenge/AMBER/blob/8a27c64ec3fc50adb9cd6f239d3a087ea39cf740/cami_amber/utils/load_data.py#L145). If you can provide a test case, I will be happy to test this.

**Comment by fernandomeyer** [comment]
Likely fixed in v2.0.5
