### ISSUE TITLE
Bug which make the option genome_coverage not usable

### ISSUE THREAD

**Issue by SantaMcCloud** [CAMI-challenge/AMBER#57]
Hello,

After the version update, the option genome_coverage it is not usable since the new code doesn't work with it. I did a PR https://github.com/CAMI-challenge/AMBER/pull/56 with a possible fix. I hope this was okay to do. Could it also be tested from your side, since it didn't see a difference in the output compare with the output from version `2.0.4`. After the review, it is also possible to release the new version?  

Thank you!

**Comment by fernandomeyer** [comment]
Hi, thank you for reporting this and the pull request. I now released v2.0.6 fixing this, let me know if there are any issues. I will close your pull request for a shorter solution 2b4daa51f2fb95231d651c19b99eef7bec7c5c7c that I used. Thanks
